### ISSUE TITLE
Consuming route from other application

### ISSUE THREAD

**Issue by albertoecf** [efriis/langchain-perplexaty#2]
Hey! I've done the [walk through ](https://www.youtube.com/watch?v=dA1cHGACXCo&ab_channel=LangChain), thanks for such detail and easy-to-follow explanation, kudos to @efriis 🎊 

I have replicated the chain + serving it with langserve. I'd need to consume [this endpoint ](https://github.com/efriis/langchain-perplexaty/blob/4fe4fef1e61191c921322c392174b26b93d8d425/app/server.py#L15), served with langserve,  from an external app. The server is working properly, I'm able to consume /playground from my web browser, but I can't consume  /invoke using postman or client app.

I've tried to follow [langserve docs](https://python.langchain.com/docs/langserve#client) on the client side, but I'm facing some errors 

Client code

```
import requests

response = requests.post(
    "http://localhost:8000/search/invoke",
    json={'input': {'topic': 'cats'}}
)
response.json()
```

Error: 

```
{'detail': [{'loc': ['__root__'],
   'msg': 'str type expected',
   'type': 'type_error.str'}]}
```

Am I missing something? Should I use other client approach? I'd appreciate any further docs / reading. 
Thanks again 😄

**Comment by efriis** [comment]
No problem - glad you enjoyed it! What this error is saying is that you are passing the input body incorrectly, so try:
```
import requests

response = requests.post(
    "http://localhost:8000/search/invoke",
    json={'input': 'cats'}
)
response.json()
```
instead

**Comment by efriis** [comment]
Also added to README here, and we added ^ todo to make these errors more readable/interpretable to the langserve roadmap!

**Comment by albertoecf** [comment]
Worked properly 🥳  Thanks again

**Comment by albertoecf** [comment]
Hey @efriis , we're building a chain that would need to accept two inputs (something similar to a dictionary). Let's say cats and a date
1. Would it make sense or should we just send one plain text? 
2. Do you have any resources / documentation for multiple inputs I could refer to? 

```
import requests

response = requests.post(
    "http://localhost:8000/search/invoke",
    json={'input': 'cats', 'date_to_search': 'some_dd-mm-yyyy' }
)
response.json()
```

Motivation: 
On this example `langchain-perplexaty`  we would like to retrieve scientific information about `input` / `topic` for a specific `date`.
